import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Swapnadeep Mohapatra</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <h2>Hi 👋 I am Swapnadeep Mohapatra! </h2>
        <Prargraph>I&apos;m currently studying in grade 12.</Prargraph>
        <Prargraph>I love to build awesome tech.</Prargraph>
        <h3>My Awards</h3>
        {/* TODO: Make Carousel */}
        <h3>My Projects</h3>
        <h3>My Talks</h3>
        <h3>My Blogs</h3>
      </Main>
    </div>
  );
};

export default Home;

const Main = styled.div`
  padding: 1rem;
`;

const Prargraph = styled.div`
  font-size: 1.2rem;
  margin: 0.5rem 0rem;
`;
